server:
  port: 8080
  contextPath: /Application
---

spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:mysql://10.225.3.252:3306/fresher
    username: fresher12
    password: 12345678
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect