package com.example.Entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "DuyAn_Projects")
public class Projects implements java.io.Serializable {

	private Integer projectId;
	private Clients clients;
	private String projectName;
	private String projectStartDate;
	private String projectEndDate;
	private String projectDescription;
	private String otherProjectDetails;
	private Set<StaffOnProjects> staffOnProjectses = new HashSet<StaffOnProjects>(0);
	private Set<StaffOnProjects> staffOnProjectses_1 = new HashSet<StaffOnProjects>(0);

	public Projects() {
	}

	public Projects(Clients clients, String projectName, String projectStartDate, String projectEndDate,
			String projectDescription, String otherProjectDetails) {
		this.clients = clients;
		this.projectName = projectName;
		this.projectStartDate = projectStartDate;
		this.projectEndDate = projectEndDate;
		this.projectDescription = projectDescription;
		this.otherProjectDetails = otherProjectDetails;
	}

	public Projects(Clients clients, String projectName, String projectStartDate, String projectEndDate,
			String projectDescription, String otherProjectDetails, Set<StaffOnProjects> staffOnProjectses,
			Set<StaffOnProjects> staffOnProjectses_1) {
		this.clients = clients;
		this.projectName = projectName;
		this.projectStartDate = projectStartDate;
		this.projectEndDate = projectEndDate;
		this.projectDescription = projectDescription;
		this.otherProjectDetails = otherProjectDetails;
		this.staffOnProjectses = staffOnProjectses;
		this.staffOnProjectses_1 = staffOnProjectses_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "project_id", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@Column(name = "project_name", nullable = false, length = 50)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_start_date", nullable = false, length = 50)
	public String getProjectStartDate() {
		return this.projectStartDate;
	}

	public void setProjectStartDate(String projectStartDate) {
		this.projectStartDate = projectStartDate;
	}

	@Column(name = "project_end_date", nullable = false, length = 50)
	public String getProjectEndDate() {
		return this.projectEndDate;
	}

	public void setProjectEndDate(String projectEndDate) {
		this.projectEndDate = projectEndDate;
	}

	@Column(name = "project_description", nullable = false, length = 50)
	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	@Column(name = "other_project_details", nullable = false, length = 100)
	public String getOtherProjectDetails() {
		return this.otherProjectDetails;
	}

	public void setOtherProjectDetails(String otherProjectDetails) {
		this.otherProjectDetails = otherProjectDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<StaffOnProjects> getStaffOnProjectses() {
		return this.staffOnProjectses;
	}

	public void setStaffOnProjectses(Set<StaffOnProjects> staffOnProjectses) {
		this.staffOnProjectses = staffOnProjectses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<StaffOnProjects> getStaffOnProjectses_1() {
		return this.staffOnProjectses_1;
	}

	public void setStaffOnProjectses_1(Set<StaffOnProjects> staffOnProjectses_1) {
		this.staffOnProjectses_1 = staffOnProjectses_1;
	}

}
