package com.example.Entity;
// Generated Sep 27, 2017 11:56:10 AM by Hibernate Tools 5.2.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServicesOnProjects generated by hbm2java
 */
@Entity
@Table(name = "DuyAn_Services_on_Projects")
public class ServicesOnProjects implements java.io.Serializable {

	private ServicesOnProjectsId id;
	private Services services;

	public ServicesOnProjects() {
	}

	public ServicesOnProjects(ServicesOnProjectsId id, Services services) {
		this.id = id;
		this.services = services;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "serviceCode", column = @Column(name = "service_code", nullable = false, length = 50)),
			@AttributeOverride(name = "projectId", column = @Column(name = "project_id", nullable = false)) })
	public ServicesOnProjectsId getId() {
		return this.id;
	}

	public void setId(ServicesOnProjectsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_code", nullable = false, insertable = false, updatable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

}
