package com.example.Entity;
// Generated Sep 27, 2017 11:56:10 AM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StaffOnProjects generated by hbm2java
 */
@Entity
@Table(name = "DuyAn_Staff_on_Projects")
public class StaffOnProjects implements java.io.Serializable {

	private Integer staffOnProjectPeriocId;
	private Projects projects;
	private RefRoles refRoles;
	private Staff staff;
	private String fromDatetime;
	private String toDatetime;
	private String hourtyRate;

	public StaffOnProjects() {
	}

	public StaffOnProjects(Projects projects, RefRoles refRoles, Staff staff, String fromDatetime, String toDatetime,
			String hourtyRate) {
		this.projects = projects;
		this.refRoles = refRoles;
		this.staff = staff;
		this.fromDatetime = fromDatetime;
		this.toDatetime = toDatetime;
		this.hourtyRate = hourtyRate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staff_on_project_perioc_id", unique = true, nullable = false)
	public Integer getStaffOnProjectPeriocId() {
		return this.staffOnProjectPeriocId;
	}

	public void setStaffOnProjectPeriocId(Integer staffOnProjectPeriocId) {
		this.staffOnProjectPeriocId = staffOnProjectPeriocId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_code", nullable = false)
	public RefRoles getRefRoles() {
		return this.refRoles;
	}

	public void setRefRoles(RefRoles refRoles) {
		this.refRoles = refRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staff_id", nullable = false)
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@Column(name = "from_datetime", nullable = false, length = 50)
	public String getFromDatetime() {
		return this.fromDatetime;
	}

	public void setFromDatetime(String fromDatetime) {
		this.fromDatetime = fromDatetime;
	}

	@Column(name = "to_datetime", nullable = false, length = 50)
	public String getToDatetime() {
		return this.toDatetime;
	}

	public void setToDatetime(String toDatetime) {
		this.toDatetime = toDatetime;
	}

	@Column(name = "hourty_rate", nullable = false, length = 50)
	public String getHourtyRate() {
		return this.hourtyRate;
	}

	public void setHourtyRate(String hourtyRate) {
		this.hourtyRate = hourtyRate;
	}

}
