package com.example.Entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "DuyAn_Staff")
public class Staff implements java.io.Serializable {

	private Integer staffId;
	private String staffName;
	private String genderMf;
	private String dateOfBirth;
	private String dailyCost;
	private String dailyRate;
	private String dateJoined;
	private String dateLeft;
	private String otherStaffDetails;
	private Set<StaffOnProjects> staffOnProjectses = new HashSet<StaffOnProjects>(0);

	public Staff() {
	}

	public Staff(String staffName, String genderMf, String dateOfBirth, String dailyCost, String dailyRate,
			String dateJoined, String dateLeft, String otherStaffDetails) {
		this.staffName = staffName;
		this.genderMf = genderMf;
		this.dateOfBirth = dateOfBirth;
		this.dailyCost = dailyCost;
		this.dailyRate = dailyRate;
		this.dateJoined = dateJoined;
		this.dateLeft = dateLeft;
		this.otherStaffDetails = otherStaffDetails;
	}

	public Staff(String staffName, String genderMf, String dateOfBirth, String dailyCost, String dailyRate,
			String dateJoined, String dateLeft, String otherStaffDetails, Set<StaffOnProjects> staffOnProjectses) {
		this.staffName = staffName;
		this.genderMf = genderMf;
		this.dateOfBirth = dateOfBirth;
		this.dailyCost = dailyCost;
		this.dailyRate = dailyRate;
		this.dateJoined = dateJoined;
		this.dateLeft = dateLeft;
		this.otherStaffDetails = otherStaffDetails;
		this.staffOnProjectses = staffOnProjectses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staff_id", unique = true, nullable = false)
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "staff_name", nullable = false, length = 50)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Column(name = "gender_MF", nullable = false, length = 50)
	public String getGenderMf() {
		return this.genderMf;
	}

	public void setGenderMf(String genderMf) {
		this.genderMf = genderMf;
	}

	@Column(name = "date_of_birth", nullable = false, length = 50)
	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "daily_cost", nullable = false, length = 50)
	public String getDailyCost() {
		return this.dailyCost;
	}

	public void setDailyCost(String dailyCost) {
		this.dailyCost = dailyCost;
	}

	@Column(name = "daily_rate", nullable = false, length = 50)
	public String getDailyRate() {
		return this.dailyRate;
	}

	public void setDailyRate(String dailyRate) {
		this.dailyRate = dailyRate;
	}

	@Column(name = "date_joined", nullable = false, length = 50)
	public String getDateJoined() {
		return this.dateJoined;
	}

	public void setDateJoined(String dateJoined) {
		this.dateJoined = dateJoined;
	}

	@Column(name = "date_left", nullable = false, length = 50)
	public String getDateLeft() {
		return this.dateLeft;
	}

	public void setDateLeft(String dateLeft) {
		this.dateLeft = dateLeft;
	}

	@Column(name = "other_staff_details", nullable = false, length = 50)
	public String getOtherStaffDetails() {
		return this.otherStaffDetails;
	}

	public void setOtherStaffDetails(String otherStaffDetails) {
		this.otherStaffDetails = otherStaffDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<StaffOnProjects> getStaffOnProjectses() {
		return this.staffOnProjectses;
	}

	public void setStaffOnProjectses(Set<StaffOnProjects> staffOnProjectses) {
		this.staffOnProjectses = staffOnProjectses;
	}

}
